![cover_1](images/giornata_1.png)

**Disclaimer!** Il materiale presente è fornito per il corso _"Python: Un Approccio Da Fisico"_ tenuto a _Maggio 2023_ per _AISF_ da _Alessandro Romancino_. Il materiale, distribuito con _licenza MIT_ è reperibile presso https://github.com/alex180500/aisf-corso-python.

# Introduzione a Python

Python è un linguaggio di programmazione ad **alto livello** ed estremamente versatile. \
_Ma perché dovrei impararlo?_ Beh... ci sono varie motivazioni:
- È un **linguaggio interpretato**
- Ha una **sintassi semplice, leggibile e concisa**
- È **ampiamente supportato** dalla comunità scientifica con librerie aggiornate continuamente
- Ha **ampio utilizzo**: semplici script, programmi, applicazioni web, GUI, machine learning, videogiochi, calcolo scientifico...
- È **software free and open source** (FOSS)

Ora riassumerò qualche comando di base, per qualsiasi dubbio trovate tutto nel [tutorial ufficiale di Python](https://docs.python.org/3/tutorial/).

In Python le variabili sono **dinamiche**. Ciò significa che uno può assegnare qualsiasi tipo alla variabile che stiamo usando, non dobbiamo dichiararle! [Clicca qui per più informazioni.](https://docs.python.org/3/library/stdtypes.html)

In [17]:
a = 10
print(type(a))
b = -15.666
print(type(b))
c = True
print(type(c))
d = 10.21093 + 5j
print(type(d))
e = [1, [10, "carlo"], False, a, b]
print(type(e))
f = "viva_aisf"
print(type(f))
g = {"palermo": "arancina", "catania": "arancino"}
print(type(g))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'complex'>
<class 'list'>
<class 'str'>
<class 'dict'>


Per stampare su terminale si usa il comando `print`, per inserire dati consiglio di imparare il formato f-string! Estremamente comodo e semplice. [Clicca qui per più informazioni.](https://docs.python.org/3/reference/lexical_analysis.html#f-strings)

In [ ]:
print("L'arancina è femmina")
print(f"Mmmmmh {d}")
print(f"Per arrotondare... {b:.2f}")
print(f"{e = }")

Per quanto riguarda il _control flow_, Python è un linguaggio estremamente flessibile e permette di effettuare cicli for su qualsiasi oggetto **iterabile**. Gli iterabili possono essere per esempio liste e dizionari. L'iterabile più semplice è `range` che crea un iterabile con la sintassi **start:stop:step**. La keyword `if` invece esegue il codice quando il suo argomento è `True`. [Clicca qui per più informazioni.](https://docs.python.org/3/tutorial/controlflow.html)

In [ ]:
for index in range(-3, 10, 2):
    print(f"{index = }")
    if index == 7:
        print(f"{index} misura massima di ogni cosa")

Una funzione che uso spessissimo in python è `enumerate`, questa permette di iterare sia su un oggetto e di avere indietro anche l'indice di iterazione. [Clicca qui per più informazioni.](https://docs.python.org/3/library/functions.html#enumerate)

In [ ]:
for idx, element in enumerate(e):
    print(idx, element)

Per accedere alle liste si usa anche qui la sintassi _start:stop:step_. Un metodo per definire funzioni estremamente utile è una **list comprehension**. [Clicca qui per più informazioni.](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

In [29]:
print(e[1:-1])
print([x**2 for x in range(10)])
print([i for i in "Lorem ipsum dolor sit amet" if i in 'aeiou'])

[[10, 'carlo'], False, 10, -15.666]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
['o', 'e', 'i', 'u', 'o', 'o', 'i', 'a', 'e']


Per quanto riguarda i dizionari invece, ci si accede usando le **keys**, è molto utile il metodo `dict.items()` per i loop. Inoltre esiste un analogo delle list comprehension chiamato **dict comprehension**. [Clicca qui per più informazioni.](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

In [6]:
print(g["palermo"])
g.items()

arancina


dict_items([('palermo', 'arancina'), ('catania', 'arancino')])

Una funzione in Python è definita da `*args` e `**kwargs`. Gli args sono **posizionali** e obbligatori, mentre i kwargs hanno un **nome** e sono opzionali. Per creare le funzioni si usa la keyword `def`. [Clicca qui per più informazioni.](https://docs.python.org/3/tutorial/controlflow.html#defining-functions)

In [10]:
def operazione(a, b, sum=True):
    if sum:
        print(f"{a} + {b} = {a+b}")
        return a + b
    else:
        print(f"{a} - {b} = {a-b}")
        return a - b

var1 = operazione(5, 2, sum=False)
var2 = operazione(3, 3)

5 - 2 = 3
3 + 3 = 6


# Pacchetti e Programmazione ad Oggetti

In Python qualsiasi cosa è un **oggetto**. Per oggetto si intende _una istanza di una classe che lo definisce, e contiene dati (attributi) e funzioni (metodi)_.

Per esempio un attributo è `complex.real` che contiene la parte reale di un numero complesso mentre un metodo è `list.append()` che permette di allungare una lista aggiungendo un elemento.

In [19]:
print(d.real)

e.append("aggiunto!")
e

10.21093


[1, [10, 'carlo'], False, 10, -15.666, 'aggiunto!']

I pacchetti di Python sono l'anima di questo linguaggio di programmazione. Per importare un pacchetto si usa la keyword `import`, fatto ciò il nome viene aggiunto al **namespace**. [Clicca qui per più informazioni.](https://docs.python.org/3/tutorial/modules.html)

In [20]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# NumPy e Numeri Random

[**NumPy**](https://numpy.org/doc/stable/user/whatisnumpy.html) è la libreria scientifica fondamentale per l'analisi dati in Python. Il suo strumento principale è l'`ndarray` che semplifica enormemente le operazioni tra matrici e vettori. [Clicca qui per più informazioni.](https://numpy.org/doc/stable/reference/index.html)

In [8]:
import numpy as np

I metodi di creazione di `ndarray` sono molteplici, quelli di base sono [`numpy.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html) che permette di trasformare qualsiasi oggetto in array, [`numpy.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) per inizializzare un array di zeri, [`numpy.arange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) per inizializzare un array equivalente a `list(range())` e, soprattutto, [`numpy.linspace(start, stop, num)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) che inizializza un array da _start_ a _stop_ con _num_ elementi equidistanziati. [Clicca qui per più informazioni.](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [31]:
y = np.array([3, 5, 7, 9, 11, 13])
x = np.linspace(1, 2, 6)
x

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

La forza di NumPy è la capacità di fare operazioni sugli array **element-wise**. Questo velocizza di molto le operazioni per l'analisi dati, soprattutto perché gli oggetti di NumPy sono internamente scritti in C (che velocizza il codice). Per accedere agli `ndarray` si usa lo **slicing** anche qui con sintassi _start:stop:step_. [Clicca qui per più informazioni.](https://numpy.org/doc/stable/reference/arrays.ndarray.html)

In [36]:
print(x + y)
print(x * 5)
x[::-1]

[ 4.   6.2  8.4 10.6 12.8 15. ]
[ 5.  6.  7.  8.  9. 10.]


array([2. , 1.8, 1.6, 1.4, 1.2, 1. ])

Per quanto riguarda la generazione di numeri random NumPy si affida a un generatore _PCG64_ per iniziarlo si usa `np.random.default_rng()`, questo generatore ha poi tante funzioni per le varie distribuzioni che ci interessano. [Clicca qui per più informazioni.](https://numpy.org/doc/stable/reference/random/generator.html)

In [9]:
rng = np.random.default_rng()
rng.integers(0, 10, size=(3, 5), endpoint=True)

array([[ 9, 10, 10, 10,  8],
       [ 8,  5,  8,  4,  1],
       [ 5,  6,  3,  4, 10]], dtype=int64)

# Esempio: Pi Greco con Metodo Montecarlo

![montecarlo](images/monte_carlo.png)

L'idea è quella di calcolare il valore di $\pi$ con il Metodo Montecarlo. Per fare ciò si generano numeri random in un quadrato e si vede se questi si trovano all'interno della circonferenza oppure no. Il numero di punti al'interno della circonferenza rispetto al numero dei punti totali è legato a $\pi$.
$$\frac{N_c}{N} = \frac{A_c}{A} = \frac{\pi r^2}{(2r)^2} = \frac{\pi}{4}$$



In [47]:
total_n = 10000000

x = rng.uniform(-1, 1, total_n)
y = rng.uniform(-1, 1, total_n)
x, y

(array([ 0.9446338 , -0.0600931 ,  0.9517022 , ..., -0.63585281,
         0.51638858,  0.46523598]),
 array([ 0.84993127, -0.96701134, -0.98036072, ..., -0.57725811,
         0.28889887,  0.8249496 ]))

In [48]:
in_circle = x**2 + y**2 < 1
in_circle

array([False,  True, False, ...,  True,  True,  True])

In [49]:
circle_n = np.sum(in_circle)
circle_n

7854277

In [50]:
pi = 4 * circle_n / total_n
pi

3.1417108